### PR TITLE
Vagrant debian

### PR DESCRIPTION
**Pull request by gilesknap**
This is marked as draft because it is alternative to and replaces the other two PRs I made.

This adds vagrant base on official Debian Bookworm and switches tansible to use DEBs instead of RPMs.

We could make a combined ansible that switches according to distro but that would be a lot of work and hard to maintain. I think we should pick a distro that works well for the training VM and make that as good as we can rather than splitting our resources across multiple distros.

To test this PR.
- clone this repo
- follow https://github.com/gilesknap/training-vm/blob/vagrant-debian/doc/vagrant.md
- Once the VM is up:-
```bash
VM_REPO="https://github.com/gilesknap/training-vm.git -b vagrant-debian" eval "$(curl -L https://raw.githubusercontent.com/gilesknap/training-vm/vagrant-debian/bootstrap.sh)"

vim training/local.yml # uncomment choice of roles and modules

./bootstrap/update.sh training
```

I have all the roles and modules building except for pvapy which has some challenges with boost. I'm sure that can be fixed.

### CODE REVIEW

**Comment by gilesknap** [comment]
closed this because of the git history - will PR again soon

**Comment by ralphlange** [comment]
See my comment on #22: What about Windows hosts? They don't have native Ansible. We need a recipe for those.

**Comment by ralphlange** [comment]
Probably not using the vagrant integration and installing+calling ansible on the guest instead would do it.

**Comment by gilesknap** [comment]
Yes, I was imagining that in general we would ship an OVA of that for those that can't easily do the first part.

But I believe that the old instructions for manual creation are still completely compatible with my changes.

**Pull request closed without merging**
