### PR TITLE
Vagrant

### PR DESCRIPTION
**Pull request by gilesknap**
Adds a vagrant config and documentation file. Also switches to Fedora 40 as the distro as I could not get Rocky working with vagrant.

WARNING: current vagrant is not compatible with VirtualBox 7.1, use 7.0.

Things to address:
- see if the community is OK with Fedora
- the following services fail to start. This does not seem to be causing significant issues.
  - mcelog.service: disabled this one
  - systemd-vconsole-setup.service: disable does not help, mask causes gnome to hang. Looks like  https://github.com/systemd/systemd/pull/32822 is a workaround but setting tty correctly in kernel args may also work?
- I had to manually add paths for java and phoebus - not sure if this is true of the original VM?

UPDATE: https://github.com/epics-training/training-vm/pull/22/commits/dd5acac610759f5bbae37ce0dbc17a33f6448450 uses ansible for initial setup and disables the offending services.

### CODE REVIEW

**Comment by gilesknap** [comment]
I'm not allowed to add reviewers so tagging those that might like to review.
@ralphlange 
@mrakitin
@shroffk

**Comment by gilesknap** [comment]
I've been using the VM to work on epics-containers support and have noticed a few video artifacts. Just turned off hw acceleration in the vm settings and the whole thing has become much more snappy.

I therefore suggest we remove the hw acceleration setting from vagrant. 

However this is likely YMMV depending on the host so I'd like to see how others find this setting. (I'm on nvidia 3090 and ubuntu 24.04 host). The original instructions already say to play with the setting so maybe we just add that to the vagrant doc file.

**Comment by ralphlange** [comment]
> However this is likely YMMV depending on the host so I'd like to see how others find this setting. (I'm on nvidia 3090 and ubuntu 24.04 host). The original instructions already say to play with the setting so maybe we just add that to the vagrant doc file.

It seemingly depends on the host.
At the training in Pohang we run it in parallel on two different laptop hosts under Windows 10: to avoid the artifacts, one of them needed the hw acceleration enabled, the other one needed it disabled.

**Comment by ralphlange** [comment]
> * Rocky did not play well with vagrant and the advantages of vagrant are huge

Agree. (Still not giving up on Rocky@Vagrant, but you have a point.)

> * the EPICS community seems to favour RPM distros and the ansible would need major fixes if we deviated from that

Well... a number of major labs are using RHEL, correct. (Does that mean "prefer"? Maybe.)

> * if you want to do containers you should choose a distro listed here: https://docs.docker.com/engine/install/#supported-platforms

That's strictly Docker, though.
Adding the Bluesky training module, the colleagues started with Docker and switched over to Podman, which worked fine for their Debian-based training containers.

> * Redhat does not play nice in containers (I tried hard 3 years ago) and is experimental support only on the above page

From my experience, when using Podman, RedHat guests are working fine.

I am all for renaming the roles to match what they're actually doing, so that we have a `podman` role for installing/using Podman etc.

> Having said that - the ansible we have is distro agnostic so we should be able to switch to another distro quite easily.

See #24, which I just created. We had informally already agreed on going in that direction.

**Comment by gilesknap** [comment]
re docker / podman. To be clear - I much prefer podman rootless but I also use the docker compose plugin with that because podman compose has not quite caught up - that is what the docker ansible role is doing in the other PR I made. 

I take your point that other distros may be better supported by podman alone.

I also think that the name of the role is fine as we also install podman-docker and more people understand what docker means.

Actually I want to take back my comment on RedHat - that was RedHat inside containers I struggled with. If you would like me to try RedHat vagrant then let me know.

**Comment by gilesknap** [comment]
I'm just doing the final testing on the Debian version.

For that I have had to switch back to rootful docker. 
- because it is the natural fit 
- because debian's podman version can't work with docker compose 2.0 
- because docker rootful is the more widely used
- and unfortunately docker rootless is *almost* brilliant and just like podman rootless but the network=host is useless 

however - I only use network host for X11 forwarding to phoebus and that is no longer required as the VM allows me to run phoebus outside. Therefore we could pick rootless docker if it works for all the VMs use cases.

**Comment by ralphlange** [comment]
"Please install Ansible on your host system."

That does not work on Windows. At least not natively. Is there a workaround?

**Comment by ralphlange** [comment]
On a Windows host, `vagrant destroy` seems to miss deleting the VM directory once you explicitly named the VM. (The "Logs" subdirectory is still there.)
The next `vagrant up` fails at the renaming step.

When using the default name, everything works fine. Likely a bug in vagrant.
@gilesknap: You don't see that on your Linux host? What vagrant version do you use?

**Comment by gilesknap** [comment]
@ralphlange 
Vagrant 2.4.1
VirtualBox 7.0.20 (7.1 does not work but a fix to vagrant is coming)

I must confess to not have considered the Windows host! (ex Microsoft employee, trying to forget)

**Comment by gilesknap** [comment]
> @gilesknap: You don't see that on your Linux host? What vagrant version do you use?

I have found vagrant to be rock solid - don't see any issues like that and I have destroyed many VMs in the last view days.

**Comment by gilesknap** [comment]
> On a Windows host, `vagrant destroy` seems to miss deleting the VM directory once you explicitly named the VM. (The "Logs" subdirectory is still there.) The next `vagrant up` fails at the renaming step.
> 
> When using the default name, everything works fine. Likely a bug in vagrant. @gilesknap: You don't see that on your Linux host? What vagrant version do you use?

I'm now seeing this when I try to build fedora but not debian. Can't work out what to delete:
```
The name of your virtual machine couldn't be set because VirtualBox
is reporting another VM with that name already exists. Most of the
time, this is because of an error with VirtualBox not cleaning up
properly. To fix this, verify that no VMs with that name do exist
(by opening the VirtualBox GUI). If they don't, then look at the
folder in the error message from VirtualBox below and remove it
if there isn't any information you need in there.

VirtualBox error:

VBoxManage: error: Could not rename the directory '/home/giles/VirtualBox VMs/Fedora-Cloud-Base-Vagrant-VirtualBox_1727296720399_37217' to '/home/giles/VirtualBox VMs/epics-training-fedora' to save the settings file (VERR_ALREADY_EXISTS)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "SaveSettings()" at line 3640 of file VBoxManageModifyVM.cpp

FAIL
```

UPDATE: it was using the same disk UID that a previous differently named VM - I'm going to try not naming the VM and let the user rename it after creation.

**Comment by ralphlange** [comment]
Exactly that.
For me, removing the "epics-training" directory did it. (That was empty except for the "Logs" subdirectory.)

For me, the issue was transient, though. Happened the day before yesterday, didn't happen yesterday.

**Comment by gilesknap** [comment]
> Also, the issue was transient. Happened the day before yesterday, didn't happen yesterday.

I only got this once - but it was clashing with another VM that used the same distro - probably the vagrant box comes with fixed UIDs for disks - but might be able to fix that.

**Comment by ralphlange** [comment]
No other VM with the same distro in my setup. Just saying.

**Comment by gilesknap** [comment]
OK well its still a mystery then!
will keep an eye on it


Closing this and moving over to https://github.com/epics-training/training-vm/pull/27

**Pull request closed without merging**
