### PR TITLE
Add Bluesky roles to Training VM

### PR DESCRIPTION
**Pull request by ralphlange**
Cleaned-up version of Marcel's PR #4.

### CODE REVIEW

**Comment by ralphlange** [comment]
Docker role: do we need both docker-compose and podman-compose?

**Comment by Mrcl3** [comment]
podman-compose should be sufficient

**Comment by Mrcl3** [comment]
By the way, the image builds for me.

**Comment by ralphlange** [comment]
Apt fails in step 4.

```
...

TASK [bluesky : Add content to .bluesky_config file] *****************************************************************
changed: [localhost] => {"backup": "", "changed": true, "msg": "line added"}

TASK [bluesky : Add a block to .bashrc only once] ********************************************************************
ok: [localhost] => {"changed": false, "msg": ""}

TASK [bluesky : Build a Docker formatted image] **********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to build image blueskytraining:latest: STEP 1/29: FROM python:3.10-slim-bullseye\nSTEP 2/29: ENV TZ=Europe/Berlin\n--> Using cache 40e0bdf2de97b8c76bc7bb0c66a94d502c70db6696770b5c5ab2f520d89e2775\n--> 40e0bdf2de97\nSTEP 3/29: RUN apt update -y && apt upgrade -y\n--> Using cache a75ff496d5dce4334a849dd1fd0fe80fd3b827745f195d75b55ec40dededf932\n--> a75ff496d5dc\nSTEP 4/29: RUN apt install -y --no-install-recommends     git     libgl1-mesa-dri     libgl1-mesa-dri     tzdata     re2c     rsync     ssh-client     nano\nReading package lists...\nBuilding dependency tree...\nReading state information...\n \nWARNING: apt does not have a stable CLI interface. Use with caution in scripts.\n\nE: Unable to locate package git\nE: Unable to locate package libgl1-mesa-dri\nE: Unable to locate package libgl1-mesa-dri\nE: Unable to locate package re2c\nE: Unable to locate package rsync\nE: Unable to locate package ssh-client\nE: Unable to locate package nano\nError: building at STEP \"RUN apt install -y --no-install-recommends     git     libgl1-mesa-dri     libgl1-mesa-dri     tzdata     re2c     rsync     ssh-client     nano\": while running runtime: exit status 100\n"}

```

**Comment by ralphlange** [comment]
Btw. Fixing the time zone to Europe/Berlin for a training in Korea???

**Comment by ralphlange** [comment]
Is it that I have to use a proxy?
Would that need a separate configuration? (In addition to environment setting and Maven settings...)

**Comment by Mrcl3** [comment]
I don't use a proxy. I changed the time to Korean and added apt update to the line that triggers error. I will try to reproduce the error in the meantime.

**Comment by ralphlange** [comment]
My point was (supposed to be) that generally fixing the time zone in a container image sounds wrong. What do you require that for?

As the epics-dev user on my VM, if I am changing into the relevant directory (`~/.bluesky`) and run `podman build .`, it works fine.
Duh.

**Comment by ralphlange** [comment]
Works fine until step 9, when the VM freezes completely.

**Comment by Mrcl3** [comment]
I created a new VM and did:

1. installed git with dnf
2. run bootstrap.sh
3. installed ansible with dnf
4. run ansible-galaxy install -r requirements.yml
5. run ansible-playbook -i hosts bluesky_playbook.yml --ask-become-pass

It runs without any problems from a brand new VM. 
About fixing the time we usually set the timezone in the container and then also expose the host's timezone and localtime to the container. 

I uploaded the image to docker hub - mbajdel136/blueskytraining:latest

**Comment by Mrcl3** [comment]
```
- name: Pull an image from Docker hub
  containers.podman.podman_image:
    name: docker.io/mbajdel136/blueskytraining
```

instead of building the image, should do the job.

**Comment by ralphlange** [comment]
NF install of Git and Ansible is done by the bootstrap script.
The instructions for creating the VM from scratch are at
https://github.com/epics-training/training-vm/blob/main/doc/creating-vm-from-scratch.md

**Comment by ralphlange** [comment]
> image from Docker hub
>   containers.podman.podman_image:
>     name: docker.io/mbajdel136/blueskytraining

Excellent. That would have been my next question. Pull the image instead of building it.

**Comment by ralphlange** [comment]
The container image build failure is related to using a proxy.

In my home setup, where I don't have to use a proxy, container image building fails if I configure a proxy (the proxy still does work in this context, it's just not mandatory) and works fine if I don't configure it and the VM uses plain NAT.

**Comment by Mrcl3** [comment]
We use containers for IOCs and Bluesky mainly on Ubuntu/Debian distributions, we had an issue that the timezone and time was not correct. The solution was to set it in the Dockerfile and then additionally expose (ro) the localtime to the container.

**Pull request merged**
