### PR TITLE
Debian and fedora

### PR DESCRIPTION
**Pull request by gilesknap**
https://github.com/epics-training/training-vm/pull/27 moved into a branch in the main repo.

This PR adds support for DEB and APT.

It defaults to debian distro but to build fedora,ubunu,rocky set the env as follows:
```bash
VAGRANT_VM_CPUS=4 VAGRANT_VM_BOX=fedora vagrant up
```

This now will run all of the roles in the guest specified in all.yml or local.yml. You can add roles and modules to local.yml before invoking vagrant - where necessary they will run as epics-dev.

### CODE REVIEW

**Comment by gilesknap** [comment]
Apologies for the broken CI. Will change it to use containers in the next few days.

**Comment by gilesknap** [comment]
Things are looking pretty good re CI. PR incoming.
image

**Comment by ralphlange** [comment]
That looks pretty great!

**Comment by ralphlange** [comment]
I'm still testing and fighting with the corporate firewall situation.
The Ansible role `catrust` that configures for the corporate firewall works on all guests now.

But the initial bootstrapping needs to be done in the free world.
Ansible configures the guest fine, but installing Ansible (which needs to happen first) doesn't work through the firewall. I don't see a viable solution for that circular dependency.

Anyway: After running the `catrust` role, the VM works and updates flawlessly on both sides.

**Comment by gilesknap** [comment]
I've seen this a couple of times in the debian in container build (always on ASYN). I think it is transient but the retries do not help in this instance. It looks like the folder that make is currently in has been deleted. 
image

**Comment by gilesknap** [comment]
With the CI merge everything is working pretty nicely with the caveats described in ci.yaml and everything.yml.

I've checked this builds in the VMs and it works for Ubuntu and Rocky, except that Rocky is also now showing boost problems with PVA. Will take a look at that on Monday and then I would be happy to merge this.

**Comment by gilesknap** [comment]
hmmm - in the CI checks above, both ubuntu and debian showed the ASYN transient issue discussed here https://github.com/epics-training/training-vm/pull/29#issuecomment-2381599358

**Comment by ralphlange** [comment]
> But the initial bootstrapping needs to be done in the free world. Ansible configures the guest fine, but installing Ansible (which needs to happen first) doesn't work through the firewall. I don't see a viable solution for that circular dependency.

I might have one.
While Ansible is not available under Windows, it is when using WSL2. Doing that and running the host-side Ansible provisioner should allow the configuration needed for the firewall to be added before calling the package manager on the guest.

**Comment by gilesknap** [comment]
> > But the initial bootstrapping needs to be done in the free world. Ansible configures the guest fine, but installing Ansible (which needs to happen first) doesn't work through the firewall. I don't see a viable solution for that circular dependency.
> 
> I might have one. While Ansible is not available under Windows, it is when using WSL2. Doing that and running the host-side Ansible provisioner should allow the configuration needed for the firewall to be added before calling the package manager on the guest.

Sorry I misread your comment before and thought you did have a solution. WSL2 might be your answer but it is another manual step and can be fiddly. WSL2 on DLS's official windows fails to have DNS at all and is useless. You may do better.

There are a few steps that we do manually in script before launching ansible and those are now all wrapped up in the single script here https://github.com/epics-training/training-vm/blob/debian-and-fedora/initial_setup.sh.

If you were able to write a little bash to do the certificate things then setup is consistent for all environments, with all pre-ansible in the one script. Looking at the ansible for `catrust` I feel the only complicated bit is the ini file change which might be achievable with a sed command.

**Comment by ralphlange** [comment]
> Sorry I misread your comment before and thought you did have a solution. WSL2 might be your answer but it is another manual step and can be fiddly. WSL2 on DLS's official windows fails to have DNS at all and is useless. You may do better.

Interesting. That must be the DLS setup, though. I have been using WSL2 instances for years as a non-admin user under Windows10 and Windows11, for podman builders/runners and to access Linux tools. (Debian, Ubuntu)
Behind the firewall, outside the firewall, anywhere.

> There are a few steps that we do manually in script before launching ansible and those are now all wrapped up in the single script here https://github.com/epics-training/training-vm/blob/debian-and-fedora/initial_setup.sh.
> 
> If you were able to write a little bash to do the certificate things then setup is consistent for all environments, with all pre-ansible in the one script. Looking at the ansible for `catrust` I feel the only complicated bit is the ini file change which might be achievable with a sed command.

The problem is that the catrust work is split between the host and the guest.

Fedora does not have the `openssl` tool installed needed to convert the cert. So we need to download and convert the cert on the host then place it into the guest and configure openssl. The openssl configuration, all file locations and the CA Cert Update script are different between Linux distro families.

**Comment by ralphlange** [comment]
> The problem is that the catrust work is split between the host and the guest.
> 
> Fedora does not have the `openssl` tool installed needed to convert the cert. So we need to download and convert the cert on the host then place it into the guest and configure openssl. The openssl configuration, all file locations and the CA Cert Update script are different between Linux distro families.

Possible shortcut:
If the catrust part is needed, the user has to provide a certificate in the right format inside the mounted `/ansible` folder.
In that case, placing the cert and the openssl configuration can be done from a single script run in the guest.

Acceptable?

**Comment by gilesknap** [comment]
> > The problem is that the catrust work is split between the host and the guest.
> > Fedora does not have the `openssl` tool installed needed to convert the cert. So we need to download and convert the cert on the host then place it into the guest and configure openssl. The openssl configuration, all file locations and the CA Cert Update script are different between Linux distro families.
> 
> Possible shortcut: If the catrust part is needed, the user has to provide a certificate in the right format inside the mounted `/ansible` folder. In that case, placing the cert and the openssl configuration can be done from a single script run in the guest.
> 
> Acceptable?

Sure that works. It adds a little manual setup but much less heavyweight that standing up WSL2!

**Comment by gilesknap** [comment]
@ralphlange 

I'm a little stuck on pvaPy. It requires boost 1.78 and although that is available in the rocky rpm repos it installs into version specific folders e.g. /usr/include/boost1.78/boost and 'make configure' can't find it. I could get the source and compile a new version of boost but that seems counter productive and will slow us down a great deal.

It is not clear to me why your original ISO installed version of rocky did not have the same issue. I note that the ISO is v 9.4 and that the box I'm starting from with vagrant is also 9.4.

Are you familiar with this issue at all?

**Comment by ralphlange** [comment]
Never seen this before.
Note that the `2024-fall-oakridge` branch of the training-collection does not include the `pvaPy` module.

If I use my manually created VM and enable `pvaPy` I run into the same issue.
After reversing the [last update](https://github.com/epics-training/training-vm/commit/cceab003dbeb41a8c49ea6768c26340f361c0c35), the build succeeds.

I think I tested the complete build, but it seems I have failed to do so. Sorry for sending you into this trap. I'm really happy that we will have CI builds soon - they are obviously necessary.

So, with standard boost on Rocky 9 being v1.75 and the packaged v1.78 having a different include location, I would file an issue upstream. Sinisa is usually very responsive and fixes things shortly. Staying on the previous version of pvaPy until a fix arrives upstream seems perfectly adequate.

**Comment by ralphlange** [comment]
Feel free to push to the PR if you see fit.
(My catrust/vagrant changes are well-separated and easy to rebase.)

**Comment by gilesknap** [comment]
Will do when the last set of tests completes I think I'm finally there. The interplay of issues between the various distros is challenging but informative!

**Comment by gilesknap** [comment]
I believe this is ready to merge if the CI passes.
Note I've added https://github.com/epics-training/training-vm/blob/debian-and-fedora/ansible/group_vars/README_distros.md to explain what works in what distro.

The TLDR is Rocky gets to build everything but needed pvaPy <=5.3.1 to do so.

**Comment by gilesknap** [comment]
@ralphlange this is all good now. I'll let you do the merge in case you'd like to tweak anything first.

Thanks for a world class training session in ansible:
- an interesting problem to solve
- great example code as a starting point

**Comment by ralphlange** [comment]
Welcome!

I know the sentiment - doing the first version in spring was my first Ansible project. :-)

**Comment by gilesknap** [comment]
We are seeing the ASYN error frequently enough to be a little annoying https://github.com/epics-training/training-vm/actions/runs/11140249148/job/30958624599.

I'm rertying the failed job and expect that to work.

**Comment by ralphlange** [comment]
`make[2]: *** O.linux-x86_64: No such file or directory.  Stop.`

Can you try running the `make` and `make clean` commands in two separate lines, not using parallel make for the latter?
Maybe my shortcut of running `make all clean` doesn't go well with the complex asyn build.

**Comment by gilesknap** [comment]
From a sample of one CI run that was good so far. 

I was a bit disappointed with ansible here though - I wanted to add an inner 'with_items' over 'all' and 'clean' and it seems that all mechanisms for looping use 'items' as the iterator unless you do with_subitems which would have meant changing the structure of the whole of the build_module task.

**Comment by gilesknap** [comment]
The epics-tools doc build just started failing. But copilot helped me out:
image

**Comment by shroffk** [comment]
Oh
This is because of a recent change I made for reproduceable build.

**Comment by shroffk** [comment]
Sorry,
I have opened a PR with the fix https://github.com/epics-training/training-vm/pull/33

**Comment by gilesknap** [comment]
@shroffk, @ralphlange Shall we merge this PR and work from there?

The CI (using docker) is working, and I just ran all 4 VMs distros against everything.yml on Windows (and now have a way to do that with a single command as per https://github.com/epics-training/training-vm/pull/32)

**Comment by ralphlange** [comment]
> @shroffk, @ralphlange Shall we merge this PR and work from there?

Yes.
The certificate nightmare only affects me for now, so that's not a blocker.
(I don't have a reasonable way to test the "other" setup, so always have to wait for the next telework or office day to test on both sides.)

**Pull request merged**
