### PR TITLE
Add pva preferences to preferences.ini.j2

### PR DESCRIPTION
**Pull request by shroffk**

### CODE REVIEW

**Comment by ralphlange** [comment]
Looks good.
(Still not tested.)

**Comment by shroffk** [comment]
Let us keep this PR open as a work in progress until we have all the right preferences.

**Comment by MJGaughran** [comment]
This (or a version similar to it) needs to be merged in order to use PVA correctly with Phoebus. It appears to work as-is for me.

**Comment by ralphlange** [comment]
If Martin says go, I'm all for it.

**Review by ralphlange — APPROVED** [review]
Looks good!

**Pull request merged**
